[Snyk] Upgrade monaco-editor from 0.34.1 to 0.51.0
axonops/axonops-workbench-cassandra pull request #423
Opened 2024-09-14 10:22 UTC by hshimizu

![snyk-top-banner](https://github.com/andygongea/OWASP-Benchmark/assets/818805/c518c423-16fe-447e-b67f-ad5a49b5d123)

<h3>Snyk has created this PR to upgrade monaco-editor from 0.34.1 to 0.51.0.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.

<hr/>

- The recommended version is **562 versions** ahead of your current version.

- The recommended version was released on **22 days ago**.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>monaco-editor</b></summary>
    <ul>
      <li>
        <b>0.51.0</b> - <a href="https://github.com/microsoft/monaco-editor/releases/tag/v0.51.0">2024-08-23</a></br><h2>Changes:</h2>
<ul>
<li><a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="2481238150" data-permission-text="Title is private" data-url="https://github.com/microsoft/monaco-editor/issues/4649" data-hovercard-type="pull_request" data-hovercard-url="/microsoft/monaco-editor/pull/4649/hovercard" href="https://github.com/microsoft/monaco-editor/pull/4649">#4649</a>: Add changes for monaco editor release 0.51.0</li>
<li><a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="2441501713" data-permission-text="Title is private" data-url="https://github.com/microsoft/monaco-editor/issues/4630" data-hovercard-type="pull_request" data-hovercard-url="/microsoft/monaco-editor/pull/4630/hovercard" href="https://github.com/microsoft/monaco-editor/pull/4630">#4630</a>: Remove locker and info-needed-closer workflows.</li>
<li><a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="2364510027" data-permission-text="Title is private" data-url="https://github.com/microsoft/monaco-editor/issues/4573" data-hovercard-type="pull_request" data-hovercard-url="/microsoft/monaco-editor/pull/4573/hovercard" href="https://github.com/microsoft/monaco-editor/pull/4573">#4573</a>: Adding some detail in MAINTAINING.md for trigger build step</li>
<li><a class="issue-link js-issue-link" data-error-text="Failed to load title" data-id="2384921027" data-permission-text="Title is private" data-url="https://github.com/microsoft/monaco-editor/issues/4586" data-hovercard-type="pull_request" data-hovercard-url="/microsoft/monaco-editor/pull/4586/hovercard" href="https://github.com/microsoft/monaco-editor/pull/4586">#4586</a>: Update Q# Keywords</li>
</ul>
<p>This list of changes was <a href="https://dev.azure.com/monacotools/Monaco/_build/results?buildId=289445&amp;view=logs" rel="nofollow">auto generated</a>.</p>
      </li>
      <li>
        <b>0.51.0-rc3</b> - <a href="https://github.com/microsoft/monaco-editor/releases/tag/v0.51.0-rc3">2024-08-22</a></br>No content.
      </li>
      <li>
        <b>0.51.0-rc2</b> - <a href="https://github.com/microsoft/monaco-editor/releases/tag/v0.51.0-rc2">2024-08-21</a></br><p>Merge pull request <a class="issue-link js-issue-link" href="https://github.com/microsoft/monaco-editor/pull/4630">#4630</a> from microsoft/dev/bhavyau/workflows</p>

<p>Remove locker and info-needed-closer workflows.</p>
      </li>
      <li>
        <b>0.51.0-rc</b> - <a href="https://github.com/microsoft/monaco-editor/releases/tag/v0.51.0-rc">2024-08-19</a></br><p>Merge pull request <a class="issue-link js-issue-link" href="https://github.com/microsoft/monaco-editor/pull/4630">#4630</a> from microsoft/dev/bhavyau/workflows</p>

<p>Remove locker and info-needed-closer workflows.</p>
      </li>
      <li>
        <b>0.51.0-dev-20240807</b> - <a href="https://github.com/microsoft/monaco-editor/releases/tag/v0.51.0-dev-20240807">2024-08-07</a></br><p>Merge pull request <a class="issue-link js-issue-link" href="https://github.com/microsoft/monaco-editor/pull/4630">#4630</a> from microsoft/dev/bhavyau/workflows</p>

<p>Remove locker and info-needed-closer workflows.</p>
      </li>
      <li>
        <b>0.51.0-dev-20240806</b> - <a href="https://github.com/microsoft/monaco-editor/releases/tag/v0.51.0-dev-20240806">2024-08-06</a></br><p>Merge pull request <a class="issue-link js-issue-link" href="https://github.com/microsoft/monaco-editor/pull/4630">#4630</a> from microsoft/dev/bhavyau/workflows</p>

<p>Remove locker and info-needed-closer workflows.</p>
      </li>
      <li>
        <b>0.51.0-dev-20240805</b> - <a href="https://github.com/microsoft/monaco-editor/releases/tag/v0.51.0-dev-20240805">2024-08-05</a></br><p>Merge pull request <a class="issue-link js-issue-link" href="https://github.com/microsoft/monaco-editor/pull/4630">#4630</a> from microsoft/dev/bhavyau/workflows</p>

<p>Remove locker and info-needed-closer workflows.</p>
      </li>
      <li>
        <b>0.51.0-dev-20240804</b> - <a href="https://github.com/microsoft/monaco-editor/releases/tag/v0.51.0-dev-20240804">2024-08-04</a></br><p>Merge pull request <a class="issue-link js-issue-link" href="https://github.com/microsoft/monaco-editor/pull/4630">#4630</a> from microsoft/dev/bhavyau/workflows</p>

<p>Remove locker and info-needed-closer workflows.</p>
      </li>
      <li>
        <b>0.51.0-dev-20240803</b> - <a href="https://github.com/microsoft/monaco-editor/releases/tag/v0.51.0-dev-20240803">2024-08-03</a></br><p>Merge pull request <a class="issue-link js-issue-link" href="https://github.com/microsoft/monaco-editor/pull/4630">#4630</a> from microsoft/dev/bhavyau/workflows</p>

<p>Remove locker and info-needed-closer workflows.</p>
      </li>
      <li>
        <b>0.51.0-dev-20240802</b> - <a href="https://github.com/microsoft/monaco-editor/releases/tag/v0.51.0-dev-20240802">2024-08-02</a></br><p>Merge pull request <a class="issue-link js-issue-link" href="https://github.com/microsoft/monaco-editor/pull/4630">#4630</a> from microsoft/dev/bhavyau/workflows</p>

<p>Remove locker and info-needed-closer workflows.</p>
      </li>
      <li>
        <b>0.51.0-dev-20240801</b> - 2024-08-01
      </li>
      <li>
        <b>0.51.0-dev-20240731</b> - 2024-07-31
      </li>
      <li>
        <b>0.51.0-dev-20240730</b> - 2024-07-30
      </li>
      <li>
        <b>0.51.0-dev-20240729</b> - 2024-07-29
      </li>
      <li>
        <b>0.51.0-dev-20240728</b> - 2024-07-28
      </li>
      <li>
        <b>0.51.0-dev-20240727</b> - 2024-07-27
      </li>
      <li>
        <b>0.51.0-dev-20240726-2</b> - 2024-07-26
      </li>
      <li>
        <b>0.51.0-dev-20240628</b> - 2024-06-28
      </li>
      <li>
        <b>0.51.0-dev-20240627</b> - 2024-06-27
      </li>
      <li>
        <b>0.51.0-dev-20240626</b> - 2024-06-26
      </li>
      <li>
        <b>0.51.0-dev-20240625</b> - 2024-06-25
      </li>
      <li>
        <b>0.51.0-dev-20240624</b> - 2024-06-24
      </li>
      <li>
        <b>0.51.0-dev-20240623</b> - 2024-06-23
      </li>
      <li>
        <b>0.51.0-dev-20240622</b> - 2024-06-22
      </li>
      <li>
        <b>0.51.0-dev-20240621</b> - 2024-06-21
      </li>
      <li>
        <b>0.50.0</b> - 2024-06-20
      </li>
      <li>
        <b>0.50.0-rc</b> - 2024-06-19
      </li>
      <li>
        <b>0.50.0-dev-20240620</b> - 2024-06-20
      </li>
      <li>
        <b>0.50.0-dev-20240619</b> - 2024-06-19
      </li>
      <li>
        <b>0.50.0-dev-20240618</b> - 2024-06-18
      </li>
      <li>
        <b>0.50.0-dev-20240617</b> - 2024-06-17
      </li>
      <li>
        <b>0.50.0-dev-20240616</b> - 2024-06-16
      </li>
      <li>
        <b>0.50.0-dev-20240615</b> - 2024-06-15
      </li>
      <li>
        <b>0.50.0-dev-20240614</b> - 2024-06-14
      </li>
      <li>
        <b>0.50.0-dev-20240613</b> - 2024-06-13
      </li>
      <li>
        <b>0.50.0-dev-20240612</b> - 2024-06-12
      </li>
      <li>
        <b>0.50.0-dev-20240611</b> - 2024-06-11
      </li>
      <li>
        <b>0.50.0-dev-20240610</b> - 2024-06-10
      </li>
      <li>
        <b>0.50.0-dev-20240609</b> - 2024-06-0 [...]

2024-09-14 12:56 UTC, mhmdkrmabd commented
This update causes a critical error and led the app to not be able to render any Monaco Editor, mostly there're break changes implemented, will check that any apply changes as needed
![image](https://github.com/user-attachments/assets/9bdda953-91b2-4cb3-b460-51fcc5c72aa4)

2024-09-16 08:12 UTC, digiserg requested changes
blocked pending @mhmdkrmabd 👍🏽

2024-09-17 08:33 UTC, millerjp commented
@mhmdkrmabd any updates on this issue?

2024-09-17 18:27 UTC, mhmdkrmabd commented
@millerjp After investigating the changes and doing multiple tests; the compatible version with the app - mainly Electron - is [v0.50.0](https://www.npmjs.com/package/monaco-editor/v/0.50.0). The latest published version `v0.51.0` is not yet compatible and throws an error unrelated to our codebase, but it's from inside the editor's module

Module `monaco-editor` will be upgraded to `v0.50.0`

2024-09-17 18:28 UTC, mhmdkrmabd commented
This PR will be closed and the module will be updated in the next PR

2024-09-17 18:28 UTC, closed without merging